data = {'sibling relationship',
        'woman director',
        'high school',
        'los angeles, california',
        'prison',
        'sequel',
        'dystopia',
        'martial arts',
        'based on novel or book',
        'family',
        'new york city',
        'based on a true story',
        'duringcreditsstinger',
        'serial killer',
        'cult film',
        'musical',
        'loss of loved one',
        'drugs',
        'murder',
        'investigation',
        'revenge',
        'friendship',
        'love',
        'aftercreditsstinger',
        'gangster',
        'based on comic',
        'violence',
        'remake',
        'police',
        'neo-noir',
        'biography',
        'action hero',
        'parent child relationship',
        'sports',
        'teenager',
        'husband wife relationship',
        'kidnapping',
        'detective',
        'london, england'}

# {'1930s',
#  '1940s',
#  '1950s',
#  '1960s',
#  '1970s',
#  '1980s',
#  '19th century',
#  'action hero',
#  'adultery',
#  'aftercreditsstinger',
#  'airplane',
#  'alcohol',
#  'alcoholic',
#  'alien',
#  'american football',
#  'amnesia',
#  'anime',
#  'assassin',
#  'assassination',
#  'baby',
#  'baseball',
#  'based on a true story',
#  'based on comic',
#  'based on novel or book',
#  'based on play or musical',
#  'based on video game',
#  'based on young adult novel',
#  'beach',
#  'best friend',
#  'betrayal',
#  'biography',
#  'blackmail',
#  'buddy cop',
#  'california',
#  'chase',
#  'chicago, illinois',
#  'christmas',
#  'church',
#  'cia',
#  'college',
#  'coming of age',
#  'competition',
#  'conspiracy',
#  'corruption',
#  'creature',
#  'criminal',
#  'cult film',
#  'dark comedy',
#  'daughter',
#  'death',
#  'demon',
#  'desert',
#  'detective',
#  'divorce',
#  'doctor',
#  'dog',
#  'dream',
#  'drug dealer',
#  'drugs',
#  'duringcreditsstinger',
#  'dying and death',
#  'dystopia',
#  'england',
#  'epic',
#  'escape',
#  'experiment',
#  'explosion',
#  'extramarital affair',
#  'faith',
#  'family',
#  'family relationships',
#  'fbi',
#  'female protagonist',
#  'fight',
#  'flashback',
#  'friends',
#  'friendship',
#  'future',
#  'gang',
#  'gangster',
#  'ghost',
#  'good versus evil',
#  'gore',
#  'gun',
#  'gunfight',
#  'heist',
#  'helicopter',
#  'hero',
#  'high school',
#  'hitman',
#  'holiday',
#  'hollywood',
#  'hospital',
#  'hostage',
#  'hotel',
#  'husband wife relationship',
#  'infidelity',
#  'investigation',
#  'island',
#  'jealousy',
#  'journalist',
#  'kidnapping',
#  'killer',
#  'kung fu',
#  'lawyer',
#  'lgbt',
#  'london, england',
#  'los angeles, california',
#  'loss of loved one',
#  'love',
#  'mafia',
#  'magic',
#  'male friendship',
#  'marriage',
#  'martial arts',
#  'military',
#  'money',
#  'monster',
#  'motorcycle',
#  'movie business',
#  'murder',
#  'music',
#  'musical',
#  'nazi',
#  'neighbor',
#  'neo-noir',
#  'new jersey',
#  'new love',
#  'new york city',
#  'nightmare',
#  'obsession',
#  'organized crime',
#  'paranoia',
#  'parent child relationship',
#  'paris, france',
#  'parody',
#  'party',
#  'police',
#  'politics',
#  'post-apocalyptic future',
#  'pregnancy',
#  'prison',
#  'prostitute',
#  'psychopath',
#  'racism',
#  'rape',
#  'relationship',
#  'remake',
#  'rescue',
#  'revenge',
#  'rivalry',
#  'road trip',
#  'robbery',
#  'robot',
#  'romance',
#  'romantic comedy',
#  'sadism',
#  'san francisco, california',
#  'satire',
#  'school',
#  'scientist',
#  'secret',
#  'sequel',
#  'serial killer',
#  'sheriff',
#  'shootout',
#  'sibling relationship',
#  'slasher',
#  'small town',
#  'soldier',
#  'space',
#  'spoof',
#  'sports',
#  'spy',
#  'student',
#  'suicide',
#  'super power',
#  'superhero',
#  'supernatural',
#  'surrealism',
#  'survival',
#  'teacher',
#  'teen movie',
#  'teenager',
#  'terrorist',
#  'texas',
#  'thief',
#  'time travel',
#  'torture',
#  'undercover',
#  'usa president',
#  'vampire',
#  'vigilante',
#  'villain',
#  'violence',
#  'washington dc, usa',
#  'wedding',
#  'witch',
#  'woman director',
#  'world war ii',
#  'writer',
#  'zombie'}
