data = {'20th Century Fox',
        'Amblin Entertainment',
        'BBC Films',
        'Canal+',
        'Columbia Pictures',
        'Dimension Films',
        'DreamWorks Pictures',
        'Dune Entertainment',
        'Film4 Productions',
        'Focus Features',
        'Fox Searchlight Pictures',
        'Lionsgate',
        'Metro-Goldwyn-Mayer',
        'Miramax',
        'New Line Cinema',
        'Orion Pictures',
        'Paramount',
        'Regency Enterprises',
        'Relativity Media',
        'Screen Gems',
        'Sony Pictures',
        'StudioCanal',
        'Summit Entertainment',
        'The Weinstein Company',
        'Touchstone Pictures',
        'TriStar Pictures',
        'United Artists',
        'Universal Pictures',
        'Village Roadshow Pictures',
        'Walt Disney Pictures',
        'Warner Bros. Pictures',
        'Working Title Films'}
